import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Aside from "./components/aside";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        <div className="flex flex-col min-h-screen">
          <nav className="bg-gray-800 text-white p-4">
            <Nav />
          </nav>
          <section className="flex flex-1 flex-col md:flex-row overflow-hidden">
            <aside className="w-full md:w-64 bg-gray-200 p-4 flex-shrink-0 overflow-y-auto">
              <Aside />
            </aside>
            <main className="flex-1 p-2 bg-white overflow-auto">
              {children}
            </main>
          </section>
          <footer className="bg-gray-800 text-white p-4">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
